device-info:
    deviceId: 1
    deviceType: 'RaspberryPi'
    mac-address: '00:0c:29:59:59:7b'
rabbit-mq:
    username: 'speedtest'
    password: '1nfield'
    send-queue: 'sendQueue'
    syslog-queue: 'syslogQueue'
message-service:
    uri: 'http://scottf.ddns.net/speedtest/'
    post-svc: 'postResult.json'

request-service:
    uri: 'http://scottf.ddns.net/speedtest/'
    get-config-svc: 'getSessionConfiguration.json'
    update-status-svc: 'updateStatus.json'
general:
    ping-timeout: 180 #seconds
    remote-timeout: 120 #seconds 
    request-config-timeout: 120 #seconds
    update-request-status-timeout: 120 #seconds
